destination: a
highlighter: rogue
markdown: kramdown
name: Javi Santana
description: Pixels are the humble bricks with which one can build cathedrals
url: http://javisantana.com
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog3"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
