destination: a
pygments: true
markdown: kramdown
name: Javi Santana
description: Pixels are the humble bricks with which one can build cathedrals
url: http://javisantana.com
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog3"
