version: 2
jobs:
  generate_digest:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: |
          export DIGEST_BRANCH=digest_`date +"%d-%m-%Y"`
          git branch -c $ >DIGEST_BRANCH
          echo "---\nlayout: micro_post\npublished: true\nname: Javisantana.com, resumen `date +"%d-%m-%Y"`\n---\n" >> _digest/$DIGEST_BRANCH.md
          git log --since=1.week --reverse --grep="^D:" --pretty=format:'---## %s%n%b ' >> _digest/$DIGEST_BRANCH.md
          git add _digest/$DIGEST_BRANCH.md
          git ci -m "digest for `date +"%d-%m-%Y"`"
          git request-pull $DIGEST_BRANCH https://github.com/javisantana/javisantana.com

workflows:
  version: 2
  build:
    jobs:
      - fetch_and_commit
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * SUN"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate_digest

